-- =========================================================================
-- SCRIPT DE CONFIGURAÇÃO COMPLETA DO SUPABASE PARA O Z PLAYER
-- Cole este script inteiro no painel do Supabase -> SQL Editor -> New Query
-- =========================================================================

-- ---------------------------------------------------------
-- 1. TABELA: notifications
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.notifications (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    target_user TEXT DEFAULT NULL, -- NULL = global, caso contrário = MAC Address
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- Políticas de Acesso
DROP POLICY IF EXISTS "Leitura de notificações para todos" ON public.notifications;
DROP POLICY IF EXISTS "Escrita e controle total de notificações" ON public.notifications;

CREATE POLICY "Leitura de notificações para todos" 
ON public.notifications FOR SELECT USING (true);

CREATE POLICY "Escrita e controle total de notificações" 
ON public.notifications FOR ALL USING (true) WITH CHECK (true);


-- ---------------------------------------------------------
-- 2. TABELA: banners
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.banners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    image_url TEXT NOT NULL,
    action_url TEXT,
    active BOOLEAN DEFAULT TRUE NOT NULL,
    ordem INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS
ALTER TABLE public.banners ENABLE ROW LEVEL SECURITY;

-- Políticas de Acesso
DROP POLICY IF EXISTS "Leitura de banners para todos" ON public.banners;
DROP POLICY IF EXISTS "Escrita e controle total de banners" ON public.banners;

CREATE POLICY "Leitura de banners para todos" 
ON public.banners FOR SELECT USING (true);

CREATE POLICY "Escrita e controle total de banners" 
ON public.banners FOR ALL USING (true) WITH CHECK (true);


-- ---------------------------------------------------------
-- 3. TABELA: app_config
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.app_config (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS
ALTER TABLE public.app_config ENABLE ROW LEVEL SECURITY;

-- Políticas de Acesso
DROP POLICY IF EXISTS "Leitura de app_config para todos" ON public.app_config;
DROP POLICY IF EXISTS "Escrita e controle total de app_config" ON public.app_config;

CREATE POLICY "Leitura de app_config para todos" 
ON public.app_config FOR SELECT USING (true);

CREATE POLICY "Escrita e controle total de app_config" 
ON public.app_config FOR ALL USING (true) WITH CHECK (true);


-- ---------------------------------------------------------
-- 4. TABELA: mac_auth
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.mac_auth (
    mac_address TEXT PRIMARY KEY,
    status BOOLEAN DEFAULT TRUE NOT NULL,
    username TEXT NOT NULL,
    password TEXT NOT NULL,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS
ALTER TABLE public.mac_auth ENABLE ROW LEVEL SECURITY;

-- Políticas de Acesso
DROP POLICY IF EXISTS "Leitura de mac_auth para todos" ON public.mac_auth;
DROP POLICY IF EXISTS "Escrita e controle total de mac_auth" ON public.mac_auth;

CREATE POLICY "Leitura de mac_auth para todos" 
ON public.mac_auth FOR SELECT USING (true);

CREATE POLICY "Escrita e controle total de mac_auth" 
ON public.mac_auth FOR ALL USING (true) WITH CHECK (true);


-- ---------------------------------------------------------
-- 5. BUCKET DE IMAGENS: storage.buckets
-- ---------------------------------------------------------
INSERT INTO storage.buckets (id, name, public)
VALUES ('banners', 'banners', true)
ON CONFLICT (id) DO NOTHING;

-- Políticas de Acesso para o Storage
DROP POLICY IF EXISTS "Permitir leitura pública de banners" ON storage.objects;
DROP POLICY IF EXISTS "Permitir upload de banners" ON storage.objects;
DROP POLICY IF EXISTS "Permitir exclusão de banners" ON storage.objects;

CREATE POLICY "Permitir leitura pública de banners"
ON storage.objects FOR SELECT
USING (bucket_id = 'banners');

CREATE POLICY "Permitir upload de banners"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'banners');

CREATE POLICY "Permitir exclusão de banners"
ON storage.objects FOR DELETE
USING (bucket_id = 'banners');
